### YamlMime:ManagedReference
items:
- uid: BOOSEapplication
  commentId: N:BOOSEapplication
  id: BOOSEapplication
  children:
  - BOOSEapplication.AppCanvas
  - BOOSEapplication.AppCommandFactory
  - BOOSEapplication.AppCommandOneParameter
  - BOOSEapplication.AppCommandTwoParameters
  - BOOSEapplication.AppParser
  - BOOSEapplication.AppStoredProgram
  - BOOSEapplication.Circle
  - BOOSEapplication.DrawToCommand
  - BOOSEapplication.MoveToCommand
  - BOOSEapplication.PenCommand
  - BOOSEapplication.Rect
  langs:
  - csharp
  - vb
  name: BOOSEapplication
  nameWithType: BOOSEapplication
  fullName: BOOSEapplication
  type: Namespace
  assemblies:
  - BOOSEapplication.Doc
references:
- uid: BOOSEapplication.AppCanvas
  commentId: T:BOOSEapplication.AppCanvas
  parent: BOOSEapplication
  isExternal: true
  href: BOOSEapplication.AppCanvas.html
  name: AppCanvas
  nameWithType: AppCanvas
  fullName: BOOSEapplication.AppCanvas
- uid: BOOSEapplication.AppCommandFactory
  commentId: T:BOOSEapplication.AppCommandFactory
  isExternal: true
  href: BOOSEapplication.AppCommandFactory.html
  name: AppCommandFactory
  nameWithType: AppCommandFactory
  fullName: BOOSEapplication.AppCommandFactory
- uid: BOOSEapplication.AppCommandOneParameter
  commentId: T:BOOSEapplication.AppCommandOneParameter
  parent: BOOSEapplication
  isExternal: true
  href: BOOSEapplication.AppCommandOneParameter.html
  name: AppCommandOneParameter
  nameWithType: AppCommandOneParameter
  fullName: BOOSEapplication.AppCommandOneParameter
- uid: BOOSEapplication.AppCommandTwoParameters
  commentId: T:BOOSEapplication.AppCommandTwoParameters
  parent: BOOSEapplication
  isExternal: true
  href: BOOSEapplication.AppCommandTwoParameters.html
  name: AppCommandTwoParameters
  nameWithType: AppCommandTwoParameters
  fullName: BOOSEapplication.AppCommandTwoParameters
- uid: BOOSEapplication.AppParser
  commentId: T:BOOSEapplication.AppParser
  isExternal: true
  href: BOOSEapplication.AppParser.html
  name: AppParser
  nameWithType: AppParser
  fullName: BOOSEapplication.AppParser
- uid: BOOSEapplication.AppStoredProgram
  commentId: T:BOOSEapplication.AppStoredProgram
  isExternal: true
  href: BOOSEapplication.AppStoredProgram.html
  name: AppStoredProgram
  nameWithType: AppStoredProgram
  fullName: BOOSEapplication.AppStoredProgram
- uid: BOOSEapplication.Circle
  commentId: T:BOOSEapplication.Circle
  isExternal: true
  href: BOOSEapplication.Circle.html
  name: Circle
  nameWithType: Circle
  fullName: BOOSEapplication.Circle
- uid: BOOSEapplication.DrawToCommand
  commentId: T:BOOSEapplication.DrawToCommand
  isExternal: true
  href: BOOSEapplication.DrawToCommand.html
  name: DrawToCommand
  nameWithType: DrawToCommand
  fullName: BOOSEapplication.DrawToCommand
- uid: BOOSEapplication.MoveToCommand
  commentId: T:BOOSEapplication.MoveToCommand
  isExternal: true
  href: BOOSEapplication.MoveToCommand.html
  name: MoveToCommand
  nameWithType: MoveToCommand
  fullName: BOOSEapplication.MoveToCommand
- uid: BOOSEapplication.PenCommand
  commentId: T:BOOSEapplication.PenCommand
  isExternal: true
  href: BOOSEapplication.PenCommand.html
  name: PenCommand
  nameWithType: PenCommand
  fullName: BOOSEapplication.PenCommand
- uid: BOOSEapplication.Rect
  commentId: T:BOOSEapplication.Rect
  isExternal: true
  href: BOOSEapplication.Rect.html
  name: Rect
  nameWithType: Rect
  fullName: BOOSEapplication.Rect
- uid: BOOSEapplication
  commentId: N:BOOSEapplication
  isExternal: true
  href: BOOSEapplication.html
  name: BOOSEapplication
  nameWithType: BOOSEapplication
  fullName: BOOSEapplication
