### YamlMime:ManagedReference
items:
- uid: BOOSEapplication.Tests
  commentId: N:BOOSEapplication.Tests
  id: BOOSEapplication.Tests
  children:
  - BOOSEapplication.Tests.AppArrayTests
  - BOOSEapplication.Tests.AppAssignTests
  - BOOSEapplication.Tests.AppCallTests
  - BOOSEapplication.Tests.AppCanvasTests
  - BOOSEapplication.Tests.AppCommandFactoryTests
  - BOOSEapplication.Tests.AppCommandOneParameterTests
  - BOOSEapplication.Tests.AppCommandTests
  - BOOSEapplication.Tests.AppCommandTwoParametersTests
  - BOOSEapplication.Tests.AppElseTests
  - BOOSEapplication.Tests.AppEndTests
  - BOOSEapplication.Tests.AppEvaluationTests
  - BOOSEapplication.Tests.AppForTests
  - BOOSEapplication.Tests.AppIfTests
  - BOOSEapplication.Tests.AppIntTests
  - BOOSEapplication.Tests.AppMethodTests
  - BOOSEapplication.Tests.AppParserTests
  - BOOSEapplication.Tests.AppPeekTests
  - BOOSEapplication.Tests.AppPokeTests
  - BOOSEapplication.Tests.AppRealTests
  - BOOSEapplication.Tests.AppStoredProgramTests
  - BOOSEapplication.Tests.AppWhileTests
  - BOOSEapplication.Tests.AppWriteTests
  - BOOSEapplication.Tests.CallFrameTests
  - BOOSEapplication.Tests.CircleTests
  - BOOSEapplication.Tests.DrawToCommandTests
  - BOOSEapplication.Tests.ErrorReportTests
  - BOOSEapplication.Tests.MoveToCommandTests
  - BOOSEapplication.Tests.NullCommandTests
  - BOOSEapplication.Tests.PenCommandTests
  - BOOSEapplication.Tests.RectTests
  langs:
  - csharp
  - vb
  name: BOOSEapplication.Tests
  nameWithType: BOOSEapplication.Tests
  fullName: BOOSEapplication.Tests
  type: Namespace
  assemblies:
  - BOOSEapplication.Tests
references:
- uid: BOOSEapplication.Tests.AppArrayTests
  commentId: T:BOOSEapplication.Tests.AppArrayTests
  href: BOOSEapplication.Tests.AppArrayTests.html
  name: AppArrayTests
  nameWithType: AppArrayTests
  fullName: BOOSEapplication.Tests.AppArrayTests
- uid: BOOSEapplication.Tests.AppAssignTests
  commentId: T:BOOSEapplication.Tests.AppAssignTests
  href: BOOSEapplication.Tests.AppAssignTests.html
  name: AppAssignTests
  nameWithType: AppAssignTests
  fullName: BOOSEapplication.Tests.AppAssignTests
- uid: BOOSEapplication.Tests.AppCallTests
  commentId: T:BOOSEapplication.Tests.AppCallTests
  href: BOOSEapplication.Tests.AppCallTests.html
  name: AppCallTests
  nameWithType: AppCallTests
  fullName: BOOSEapplication.Tests.AppCallTests
- uid: BOOSEapplication.Tests.AppCanvasTests
  commentId: T:BOOSEapplication.Tests.AppCanvasTests
  href: BOOSEapplication.Tests.AppCanvasTests.html
  name: AppCanvasTests
  nameWithType: AppCanvasTests
  fullName: BOOSEapplication.Tests.AppCanvasTests
- uid: BOOSEapplication.Tests.AppCommandFactoryTests
  commentId: T:BOOSEapplication.Tests.AppCommandFactoryTests
  href: BOOSEapplication.Tests.AppCommandFactoryTests.html
  name: AppCommandFactoryTests
  nameWithType: AppCommandFactoryTests
  fullName: BOOSEapplication.Tests.AppCommandFactoryTests
- uid: BOOSEapplication.Tests.AppCommandOneParameterTests
  commentId: T:BOOSEapplication.Tests.AppCommandOneParameterTests
  href: BOOSEapplication.Tests.AppCommandOneParameterTests.html
  name: AppCommandOneParameterTests
  nameWithType: AppCommandOneParameterTests
  fullName: BOOSEapplication.Tests.AppCommandOneParameterTests
- uid: BOOSEapplication.Tests.AppCommandTests
  commentId: T:BOOSEapplication.Tests.AppCommandTests
  href: BOOSEapplication.Tests.AppCommandTests.html
  name: AppCommandTests
  nameWithType: AppCommandTests
  fullName: BOOSEapplication.Tests.AppCommandTests
- uid: BOOSEapplication.Tests.AppCommandTwoParametersTests
  commentId: T:BOOSEapplication.Tests.AppCommandTwoParametersTests
  href: BOOSEapplication.Tests.AppCommandTwoParametersTests.html
  name: AppCommandTwoParametersTests
  nameWithType: AppCommandTwoParametersTests
  fullName: BOOSEapplication.Tests.AppCommandTwoParametersTests
- uid: BOOSEapplication.Tests.AppElseTests
  commentId: T:BOOSEapplication.Tests.AppElseTests
  href: BOOSEapplication.Tests.AppElseTests.html
  name: AppElseTests
  nameWithType: AppElseTests
  fullName: BOOSEapplication.Tests.AppElseTests
- uid: BOOSEapplication.Tests.AppEndTests
  commentId: T:BOOSEapplication.Tests.AppEndTests
  href: BOOSEapplication.Tests.AppEndTests.html
  name: AppEndTests
  nameWithType: AppEndTests
  fullName: BOOSEapplication.Tests.AppEndTests
- uid: BOOSEapplication.Tests.AppEvaluationTests
  commentId: T:BOOSEapplication.Tests.AppEvaluationTests
  href: BOOSEapplication.Tests.AppEvaluationTests.html
  name: AppEvaluationTests
  nameWithType: AppEvaluationTests
  fullName: BOOSEapplication.Tests.AppEvaluationTests
- uid: BOOSEapplication.Tests.AppForTests
  commentId: T:BOOSEapplication.Tests.AppForTests
  href: BOOSEapplication.Tests.AppForTests.html
  name: AppForTests
  nameWithType: AppForTests
  fullName: BOOSEapplication.Tests.AppForTests
- uid: BOOSEapplication.Tests.AppIfTests
  commentId: T:BOOSEapplication.Tests.AppIfTests
  href: BOOSEapplication.Tests.AppIfTests.html
  name: AppIfTests
  nameWithType: AppIfTests
  fullName: BOOSEapplication.Tests.AppIfTests
- uid: BOOSEapplication.Tests.AppIntTests
  commentId: T:BOOSEapplication.Tests.AppIntTests
  href: BOOSEapplication.Tests.AppIntTests.html
  name: AppIntTests
  nameWithType: AppIntTests
  fullName: BOOSEapplication.Tests.AppIntTests
- uid: BOOSEapplication.Tests.AppMethodTests
  commentId: T:BOOSEapplication.Tests.AppMethodTests
  href: BOOSEapplication.Tests.AppMethodTests.html
  name: AppMethodTests
  nameWithType: AppMethodTests
  fullName: BOOSEapplication.Tests.AppMethodTests
- uid: BOOSEapplication.Tests.AppParserTests
  commentId: T:BOOSEapplication.Tests.AppParserTests
  href: BOOSEapplication.Tests.AppParserTests.html
  name: AppParserTests
  nameWithType: AppParserTests
  fullName: BOOSEapplication.Tests.AppParserTests
- uid: BOOSEapplication.Tests.AppPeekTests
  commentId: T:BOOSEapplication.Tests.AppPeekTests
  href: BOOSEapplication.Tests.AppPeekTests.html
  name: AppPeekTests
  nameWithType: AppPeekTests
  fullName: BOOSEapplication.Tests.AppPeekTests
- uid: BOOSEapplication.Tests.AppPokeTests
  commentId: T:BOOSEapplication.Tests.AppPokeTests
  href: BOOSEapplication.Tests.AppPokeTests.html
  name: AppPokeTests
  nameWithType: AppPokeTests
  fullName: BOOSEapplication.Tests.AppPokeTests
- uid: BOOSEapplication.Tests.AppRealTests
  commentId: T:BOOSEapplication.Tests.AppRealTests
  href: BOOSEapplication.Tests.AppRealTests.html
  name: AppRealTests
  nameWithType: AppRealTests
  fullName: BOOSEapplication.Tests.AppRealTests
- uid: BOOSEapplication.Tests.AppStoredProgramTests
  commentId: T:BOOSEapplication.Tests.AppStoredProgramTests
  href: BOOSEapplication.Tests.AppStoredProgramTests.html
  name: AppStoredProgramTests
  nameWithType: AppStoredProgramTests
  fullName: BOOSEapplication.Tests.AppStoredProgramTests
- uid: BOOSEapplication.Tests.AppWhileTests
  commentId: T:BOOSEapplication.Tests.AppWhileTests
  href: BOOSEapplication.Tests.AppWhileTests.html
  name: AppWhileTests
  nameWithType: AppWhileTests
  fullName: BOOSEapplication.Tests.AppWhileTests
- uid: BOOSEapplication.Tests.AppWriteTests
  commentId: T:BOOSEapplication.Tests.AppWriteTests
  href: BOOSEapplication.Tests.AppWriteTests.html
  name: AppWriteTests
  nameWithType: AppWriteTests
  fullName: BOOSEapplication.Tests.AppWriteTests
- uid: BOOSEapplication.Tests.CallFrameTests
  commentId: T:BOOSEapplication.Tests.CallFrameTests
  href: BOOSEapplication.Tests.CallFrameTests.html
  name: CallFrameTests
  nameWithType: CallFrameTests
  fullName: BOOSEapplication.Tests.CallFrameTests
- uid: BOOSEapplication.Tests.CircleTests
  commentId: T:BOOSEapplication.Tests.CircleTests
  href: BOOSEapplication.Tests.CircleTests.html
  name: CircleTests
  nameWithType: CircleTests
  fullName: BOOSEapplication.Tests.CircleTests
- uid: BOOSEapplication.Tests.DrawToCommandTests
  commentId: T:BOOSEapplication.Tests.DrawToCommandTests
  href: BOOSEapplication.Tests.DrawToCommandTests.html
  name: DrawToCommandTests
  nameWithType: DrawToCommandTests
  fullName: BOOSEapplication.Tests.DrawToCommandTests
- uid: BOOSEapplication.Tests.ErrorReportTests
  commentId: T:BOOSEapplication.Tests.ErrorReportTests
  href: BOOSEapplication.Tests.ErrorReportTests.html
  name: ErrorReportTests
  nameWithType: ErrorReportTests
  fullName: BOOSEapplication.Tests.ErrorReportTests
- uid: BOOSEapplication.Tests.MoveToCommandTests
  commentId: T:BOOSEapplication.Tests.MoveToCommandTests
  href: BOOSEapplication.Tests.MoveToCommandTests.html
  name: MoveToCommandTests
  nameWithType: MoveToCommandTests
  fullName: BOOSEapplication.Tests.MoveToCommandTests
- uid: BOOSEapplication.Tests.NullCommandTests
  commentId: T:BOOSEapplication.Tests.NullCommandTests
  href: BOOSEapplication.Tests.NullCommandTests.html
  name: NullCommandTests
  nameWithType: NullCommandTests
  fullName: BOOSEapplication.Tests.NullCommandTests
- uid: BOOSEapplication.Tests.PenCommandTests
  commentId: T:BOOSEapplication.Tests.PenCommandTests
  href: BOOSEapplication.Tests.PenCommandTests.html
  name: PenCommandTests
  nameWithType: PenCommandTests
  fullName: BOOSEapplication.Tests.PenCommandTests
- uid: BOOSEapplication.Tests.RectTests
  commentId: T:BOOSEapplication.Tests.RectTests
  href: BOOSEapplication.Tests.RectTests.html
  name: RectTests
  nameWithType: RectTests
  fullName: BOOSEapplication.Tests.RectTests
